-- Reversão da Fase 2: volta as políticas ao acesso aberto (qualquer um com a chave pública). Use só se o app travar.

alter policy "acesso por papel" on public.pauta_assuntos to public using (true) with check (true);
alter policy "acesso por papel" on public.pauta_setores to public using (true) with check (true);
alter policy "leitura por papel (outros modulos)" on public.pauta_setores to public using (true);
alter policy "acesso por papel" on public.pauta_membros to public using (true) with check (true);
alter policy "leitura por papel (outros modulos)" on public.pauta_membros to public using (true);
alter policy "acesso por papel" on public.checkin_assuntos to public using (true) with check (true);
alter policy "leitura por papel (outros modulos)" on public.checkin_assuntos to public using (true);
alter policy "acesso por papel" on public.checkin_reunioes to public using (true) with check (true);
alter policy "acesso por papel" on public.rdo_snapshot to public using (true) with check (true);
alter policy "leitura por papel (outros modulos)" on public.rdo_snapshot to public using (true);
alter policy "select por papel" on public.rdo_locais to public using (true);
alter policy "insert por papel" on public.rdo_locais to public with check (true);
alter policy "update por papel" on public.rdo_locais to public using (true) with check (true);
alter policy "delete por papel" on public.rdo_locais to public using (true);
alter policy "select por papel" on public.custos_entradas to public using (true);
alter policy "insert por papel" on public.custos_entradas to public with check (true);
alter policy "update por papel" on public.custos_entradas to public using (true) with check (true);
alter policy "leitura por papel (outros modulos)" on public.custos_entradas to public using (true);
alter policy "select por papel" on public.custos_entradas_fotos to public using (true);
alter policy "insert por papel" on public.custos_entradas_fotos to public with check (true);
alter policy "leitura por papel (outros modulos)" on public.custos_entradas_fotos to public using (true);
alter policy "select por papel" on public.custos_catalogo to public using (true);
alter policy "insert por papel" on public.custos_catalogo to public with check (true);
alter policy "update por papel" on public.custos_catalogo to public using (true) with check (true);
alter policy "leitura por papel (outros modulos)" on public.custos_catalogo to public using (true);
alter policy "acesso por papel" on public.custos_notas_fiscais to public using (true) with check (true);
alter policy "acesso por papel" on public.custos_itens_nf to public using (true) with check (true);
alter policy "acesso por papel" on public.medicao_contratos to public using (true) with check (true);
alter policy "acesso por papel" on public.documentos to public using (true) with check (true);
alter policy "acesso por papel" on public.documento_notas_manuais to public using (true) with check (true);
alter policy "acesso por papel" on public.eap_itens to public using (true) with check (true);
alter policy "acesso por papel" on public.planejamento_cronogramas to public using (true) with check (true);
alter policy "acesso por papel" on public.planejamento_atividades to public using (true) with check (true);
alter policy "acesso por papel" on public.planejamento_restricoes to public using (true) with check (true);
alter policy "acesso por papel" on public.manutencao_mural to public using (true) with check (true);
alter policy "acesso por papel" on public.reuniao_atas to public using (true) with check (true);
alter policy "acesso por papel" on public.requisicoes_compra to public using (true) with check (true);
alter policy "acesso por papel" on public.suprimentos_cotacoes to public using (true) with check (true);
alter policy "acesso por papel" on public.suprimentos_pedidos to public using (true) with check (true);
alter policy "acesso por papel" on public.obra_config to public using (true) with check (true);
alter policy "leitura por papel" on public.obra_config to public using (true);
